### ISSUE TITLE
build: Unclear how to build and serve non-default docs

### ISSUE THREAD

**Issue by leaf-node** [VeryGoodOpenSource/very_good_docs_site#118]
**Description**

When I try to build and serve the docs locally, I just get a demo site.

```
podman run -it --net host --mount=type=bind,source=very_good_docs_site/,destination=/srv node /bin/bash
```

```
cd /srv/src/very_good_docs_site/
npm install
npm run build
```

```
npm run serve
npm start
```

**Requirements**

The compiled site should show up. Maybe I'm doing this wrong. Thanks for your help.

**Comment by renancaraujo** [comment]
Hello @leaf-node , what steps did you follow to generate your project?

You can use as a standalone brick: https://brickhub.dev/bricks/very_good_docs_site#usage
Or via Very good CLI: https://cli.vgv.dev/docs/templates/docs_site

**Comment by leaf-node** [comment]
I only tried the method in my original post, which was basically running npm commands from the repo readme file, but wrapped in a podman container. I haven't tried the other approaches at this time, but if they work, it would be helpful to include them in the main readme file. Thanks! :smile:

**Comment by alestiago** [comment]
We're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue. I'll reopen it there once I verify that the documentation is still needed.
